global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: /metrics

  - job_name: 'frontend-service'
    static_configs:
      - targets: ['frontend:4000']
    metrics_path: /metrics

  - job_name: 'business-service'
    static_configs:
      - targets: ['business_module:8002']
    metrics_path: /metrics

  - job_name: 'payments-service'
    static_configs:
      - targets: ['payments_module:8003']
    metrics_path: /metrics

  - job_name: 'tasks-service'
    static_configs:
      - targets: ['tasks_module:8004']
    metrics_path: /metrics

  - job_name: 'teams-service'
    static_configs:
      - targets: ['teams_module:8005']
    metrics_path: /metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']